#!/usr/bin/env bun
/**
 * Generates `historian-prompt.generated.ts` from `historian-prompt.source.md`.
 *
 * The v8.7.5 historian system prompt (validated across the replay experiments,
 * reconciled to the locked 4-seed-floor reference model) is the editable source
 * of truth. We emit it as a TS string constant rather than reading the .md at
 * runtime because bundling non-TS assets into dist/index.js is fragile (see the
 * @huggingface/transformers bundling history). The prompt contains ~306
 * backticks and would break a naive template literal, so we escape backticks
 * and `${` defensively before embedding.
 *
 * Regenerate after editing the source prompt:
 *   bun run packages/plugin/scripts/build-historian-prompt.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { V2_MEMORY_CATEGORIES } from "../src/features/magic-context/memory/constants";

const here = dirname(fileURLToPath(import.meta.url));
const SRC = resolve(here, "../src/hooks/magic-context/historian-prompt.source.md");
const OUT = resolve(here, "../src/hooks/magic-context/historian-prompt.generated.ts");

const raw = readFileSync(SRC, "utf-8").trimEnd();

if (!raw.startsWith("# Historian")) {
  throw new Error("build-historian-prompt: source does not start with '# Historian' header");
}
// Sanity: the locked reconciliation must be present (guards against a stale source copy).
if (!raw.includes("always present (a small permanent calibration floor)")) {
  throw new Error(
    "build-historian-prompt: source missing the 4-seed-floor reconciliation — refusing to emit a stale 'phases down/disappears' prompt",
  );
}
// Sanity: the output envelope the parser depends on must exist.
for (const marker of ["<compartments>", "<unprocessed_from>", "<facts>"]) {
  if (!raw.includes(marker)) {
    throw new Error(`build-historian-prompt: source missing required output marker '${marker}'`);
  }
}

const expectedCategories = [...V2_MEMORY_CATEGORIES];
const headings = [...raw.matchAll(/^#### `([A-Z][A-Z0-9_]*)`$/gm)].map((match) => match[1]);
const emitted = [...raw.matchAll(/^<([A-Z][A-Z0-9_]*)>$/gm)].map((match) => match[1]);
if (JSON.stringify(headings) !== JSON.stringify(expectedCategories) ||
    JSON.stringify(emitted) !== JSON.stringify(expectedCategories)) {
  throw new Error(`build-historian-prompt: category drift: expected ${expectedCategories.join(", ")}; headings ${headings.join(", ")}; emitted ${emitted.join(", ")}`);
}

// Escape for a TS template literal: backslash, backtick, then ${.
const escaped = raw
  .replace(/\\/g, "\\\\")
  .replace(/`/g, "\\`")
  .replace(/\$\{/g, "\\${");

const out = `// AUTO-GENERATED by scripts/build-historian-prompt.ts from historian-prompt.source.md
// DO NOT EDIT BY HAND. Regenerate: bun run packages/plugin/scripts/build-historian-prompt.ts
//
// The v8.7.5 historian system prompt (validated in the replay experiments,
// reconciled to the 4-seed permanent-floor reference model). Edit the .md
// source, not this file.

export const COMPARTMENT_AGENT_SYSTEM_PROMPT = \`${escaped}\`;
`;

writeFileSync(OUT, out, "utf-8");
console.log(
  `build-historian-prompt: emitted ${raw.length} chars → ${OUT}`,
);
