#!/usr/bin/env bun
/** Generates the bundled ongoing-interaction historian prompt from its Markdown source. */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const source = resolve(here, "../src/hooks/magic-context/ongoing-interaction-historian-prompt.source.md");
const output = resolve(here, "../src/hooks/magic-context/ongoing-interaction-historian-prompt.generated.ts");
const raw = readFileSync(source, "utf8").trimEnd();

for (const marker of ["# Historian — Ongoing Interaction Memory Domain", "<SEMANTIC_MEMORY>", "<unprocessed_from>"]) {
  if (!raw.includes(marker)) throw new Error(`ongoing-interaction prompt missing required marker ${marker}`);
}

const escaped = raw.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
writeFileSync(
  output,
  `// AUTO-GENERATED by scripts/build-ongoing-interaction-historian-prompt.ts\n// DO NOT EDIT BY HAND.\n\nexport const ONGOING_INTERACTION_HISTORIAN_SYSTEM_PROMPT = \`${escaped}\`;\n`,
  "utf8",
);
console.log(`build-ongoing-interaction-historian-prompt: emitted ${raw.length} chars → ${output}`);
