import { describe, expect, it } from "bun:test";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { SessionManager } from "@earendil-works/pi-coding-agent";
import { resolvePiStableId } from "./read-session-pi";

describe("resolvePiStableId — precedence", () => {
	const msg = { role: "assistant", timestamp: 1700 };

	it("prefers entryIdByRef (reference identity) over everything", () => {
		const ref = new Map<object, string>([[msg, "entry-real"]]);
		expect(resolvePiStableId(msg, 3, ["positional-id"], ref)).toBe(
			"entry-real",
		);
	});

	it("falls back to positional entryIds when ref misses", () => {
		// A cloned object (different ref) is NOT in the ref map — this is the
		// tagging-clone case F1 calls out. Positional must cover it.
		const ref = new Map<object, string>([[{ other: true }, "entry-other"]]);
		expect(resolvePiStableId(msg, 2, ["a", "b", "entry-pos"], ref)).toBe(
			"entry-pos",
		);
	});

	it("falls back to the pi-msg index id when no real id resolves", () => {
		expect(resolvePiStableId(msg, 5)).toBe("pi-msg-5-1700-assistant");
	});

	it("omits the timestamp segment when the message has none", () => {
		expect(resolvePiStableId({ role: "user" }, 4)).toBe("pi-msg-4-user");
	});

	it("uses role=unknown when role is absent", () => {
		expect(resolvePiStableId({ timestamp: 9 }, 1)).toBe("pi-msg-1-9-unknown");
	});

	it("real SessionEntry ids generated by Pi cannot collide with the synthesized pi-msg-* lexical form", () => {
		const directory = mkdtempSync(join(tmpdir(), "pi-entry-id-scheme-"));
		try {
			const manager = SessionManager.create(directory, directory);
			const ids = Array.from({ length: 256 }, (_, index) =>
				manager.appendMessage({
					role: "user",
					content: `message ${index}`,
					timestamp: index,
				} as never),
			);
			expect(new Set(ids).size).toBe(ids.length);
			for (const id of ids) {
				expect(id).toMatch(/^[0-9a-f]{8}(?:-[0-9a-f-]{27})?$/);
				expect(id).not.toMatch(/^pi-msg-/);
			}
		} finally {
			rmSync(directory, { recursive: true, force: true });
		}
	});

	it("returns undefined for non-object messages", () => {
		expect(resolvePiStableId(null, 0)).toBeUndefined();
		expect(resolvePiStableId("nope", 0)).toBeUndefined();
		expect(resolvePiStableId(undefined, 0)).toBeUndefined();
	});

	it("skips empty/whitespace positional and ref ids, falling through to index", () => {
		const ref = new Map<object, string>([[msg, ""]]);
		expect(resolvePiStableId(msg, 7, [""], ref)).toBe(
			"pi-msg-7-1700-assistant",
		);
	});
});

describe("resolvePiStableId — index-shift stability (the core invariant)", () => {
	// THE bug this refactor fixes: when the visible message array is structurally
	// shifted (compaction-marker prefix trim, custom_message inserts), an
	// index-based id drifts → persisted state keyed on it orphans → cache bust.
	// A real SessionEntry id is position-independent, so the SAME message keeps
	// the SAME id across the shift.
	it("keeps a stable id for the same message across an index shift when a real entry id resolves", () => {
		const m = { role: "assistant", timestamp: 42 };

		// Pass 1: message sits at index 5 (e.g. before a prefix trim).
		const entryIdsPass1 = Array(6).fill(undefined);
		entryIdsPass1[5] = "entry-ABC";
		const idPass1 = resolvePiStableId(m, 5, entryIdsPass1);

		// Pass 2: a prefix of 3 messages was trimmed; the SAME message is now at
		// index 2, and the positional array reflects the new position.
		const entryIdsPass2 = Array(3).fill(undefined);
		entryIdsPass2[2] = "entry-ABC";
		const idPass2 = resolvePiStableId(m, 2, entryIdsPass2);

		expect(idPass1).toBe("entry-ABC");
		expect(idPass2).toBe("entry-ABC");
		expect(idPass1).toBe(idPass2); // stable across the shift — no drift.
	});

	it("DOES drift for a synthetic/unresolved message (acceptable — no real id exists)", () => {
		// A message with no resolvable real entry id can only use the index
		// fallback, which legitimately differs across positions. This is the
		// accepted residual (synthetic compaction summaries / custom_message).
		const m = { role: "user", timestamp: 7 };
		expect(resolvePiStableId(m, 5)).not.toBe(resolvePiStableId(m, 2));
	});
});

describe("resolvePiStableId — consistency invariant (F1)", () => {
	// The transcript-tag path and the reasoning-lookup path MUST resolve the same
	// id for the same message on the same pass, or reasoning's messageIdToMaxTag
	// lookup silently misses. Both now route through this one function with the
	// same inputs — INCLUDING when tagging cloned the object (ref miss → positional
	// covers it identically).
	it("transcript path and reasoning path agree even when the object was cloned (ref miss)", () => {
		const original = { role: "assistant", timestamp: 100 };
		const cloned = { ...original }; // what tagging does to working[idx]
		const entryIds: (string | undefined)[] = [];
		entryIds[4] = "entry-XYZ";
		// entryIdByRef only knows the ORIGINAL ref (built pre-clone in some paths)
		const ref = new Map<object, string>([[original, "entry-XYZ"]]);

		// Transcript path resolves the original (or via positional).
		const transcriptId = resolvePiStableId(original, 4, entryIds, ref);
		// Reasoning path runs on the CLONED working object — ref misses, positional
		// must yield the identical id.
		const reasoningId = resolvePiStableId(cloned, 4, entryIds, ref);

		expect(transcriptId).toBe("entry-XYZ");
		expect(reasoningId).toBe("entry-XYZ");
		expect(transcriptId).toBe(reasoningId);
	});
});
