// AUTO-GENERATED by scripts/generate-mural-font.ts from pxpipe/assets/Spleen-5x8.otb
// DO NOT EDIT BY HAND. Regenerate: bun packages/plugin/scripts/generate-mural-font.ts
//
// Spleen 5x8 bitmap data is Copyright (c) 2018-2026, Frederic Cambus.
// All rights reserved. Spleen is distributed under the BSD-2-Clause license:
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   * Redistributions of source code must retain the above copyright notice,
//     this list of conditions and the following disclaimer.
//   * Redistributions in binary form must reproduce the above copyright notice,
//     this list of conditions and the following disclaimer in the documentation
//     and/or other materials provided with the distribution.
//   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
//   AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
//   IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
//   ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
//   LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
//   CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
//   SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
//   INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
//   CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
//   ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
//   POSSIBILITY OF SUCH DAMAGE.
//
// The Spleen font supplies printable ASCII and U+2500; the additional mural
// cue marks use deterministic 5x8 companion patterns because they are not
// mapped by the Spleen 5x8 OTB.
//
// Source: pxpipe/assets/Spleen-5x8.otb

export interface MuralFontGlyph {
    readonly rows: readonly number[];
    readonly width: number;
    readonly advance: number;
}

export const MURAL_FONT_CELL_WIDTH = 5;
export const MURAL_FONT_CELL_HEIGHT = 8;
export const MURAL_FONT_LINE_PITCH = 9;
export const MURAL_FONT_GLYPHS: Readonly<Record<string, MuralFontGlyph>> = {
    " ": { rows: [0, 0, 0, 0, 0, 0, 0, 0], width: 5, advance: 5 },
    "!": { rows: [4, 4, 4, 4, 4, 0, 4, 0], width: 5, advance: 5 },
    '"': { rows: [10, 10, 10, 0, 0, 0, 0, 0], width: 5, advance: 5 },
    "#": { rows: [0, 10, 31, 10, 10, 31, 10, 0], width: 5, advance: 5 },
    $: { rows: [4, 14, 20, 12, 6, 6, 28, 4], width: 5, advance: 5 },
    "%": { rows: [2, 18, 20, 4, 8, 10, 18, 16], width: 5, advance: 5 },
    "&": { rows: [4, 10, 10, 12, 21, 18, 13, 0], width: 5, advance: 5 },
    "'": { rows: [4, 4, 4, 0, 0, 0, 0, 0], width: 5, advance: 5 },
    "(": { rows: [2, 4, 8, 8, 8, 8, 4, 2], width: 5, advance: 5 },
    ")": { rows: [8, 4, 2, 2, 2, 2, 4, 8], width: 5, advance: 5 },
    "*": { rows: [0, 0, 18, 12, 30, 12, 18, 0], width: 5, advance: 5 },
    "+": { rows: [0, 0, 4, 4, 31, 4, 4, 0], width: 5, advance: 5 },
    ",": { rows: [0, 0, 0, 0, 0, 4, 4, 8], width: 5, advance: 5 },
    "-": { rows: [0, 0, 0, 0, 30, 0, 0, 0], width: 5, advance: 5 },
    ".": { rows: [0, 0, 0, 0, 0, 0, 4, 0], width: 5, advance: 5 },
    "/": { rows: [2, 2, 4, 4, 8, 8, 16, 16], width: 5, advance: 5 },
    "0": { rows: [0, 12, 18, 22, 26, 18, 12, 0], width: 5, advance: 5 },
    "1": { rows: [0, 4, 12, 4, 4, 4, 14, 0], width: 5, advance: 5 },
    "2": { rows: [0, 12, 18, 2, 12, 16, 30, 0], width: 5, advance: 5 },
    "3": { rows: [0, 12, 18, 4, 2, 18, 12, 0], width: 5, advance: 5 },
    "4": { rows: [0, 16, 20, 20, 30, 4, 4, 0], width: 5, advance: 5 },
    "5": { rows: [0, 30, 16, 28, 2, 2, 28, 0], width: 5, advance: 5 },
    "6": { rows: [0, 12, 16, 28, 18, 18, 12, 0], width: 5, advance: 5 },
    "7": { rows: [0, 30, 18, 2, 4, 8, 8, 0], width: 5, advance: 5 },
    "8": { rows: [0, 12, 18, 12, 18, 18, 12, 0], width: 5, advance: 5 },
    "9": { rows: [0, 12, 18, 18, 14, 2, 12, 0], width: 5, advance: 5 },
    ":": { rows: [0, 0, 0, 4, 0, 0, 4, 0], width: 5, advance: 5 },
    ";": { rows: [0, 0, 0, 4, 0, 4, 4, 8], width: 5, advance: 5 },
    "<": { rows: [0, 2, 4, 8, 8, 4, 2, 0], width: 5, advance: 5 },
    "=": { rows: [0, 0, 0, 30, 0, 30, 0, 0], width: 5, advance: 5 },
    ">": { rows: [0, 8, 4, 2, 2, 4, 8, 0], width: 5, advance: 5 },
    "?": { rows: [12, 18, 2, 4, 8, 0, 8, 0], width: 5, advance: 5 },
    "@": { rows: [0, 12, 18, 22, 22, 16, 14, 0], width: 5, advance: 5 },
    A: { rows: [0, 12, 18, 18, 30, 18, 18, 0], width: 5, advance: 5 },
    B: { rows: [0, 28, 18, 28, 18, 18, 28, 0], width: 5, advance: 5 },
    C: { rows: [0, 14, 16, 16, 16, 16, 14, 0], width: 5, advance: 5 },
    D: { rows: [0, 28, 18, 18, 18, 18, 28, 0], width: 5, advance: 5 },
    E: { rows: [0, 14, 16, 28, 16, 16, 14, 0], width: 5, advance: 5 },
    F: { rows: [0, 14, 16, 16, 28, 16, 16, 0], width: 5, advance: 5 },
    G: { rows: [0, 14, 16, 22, 18, 18, 14, 0], width: 5, advance: 5 },
    H: { rows: [0, 18, 18, 30, 18, 18, 18, 0], width: 5, advance: 5 },
    I: { rows: [0, 14, 4, 4, 4, 4, 14, 0], width: 5, advance: 5 },
    J: { rows: [0, 14, 4, 4, 4, 4, 24, 0], width: 5, advance: 5 },
    K: { rows: [0, 18, 18, 28, 18, 18, 18, 0], width: 5, advance: 5 },
    L: { rows: [0, 16, 16, 16, 16, 16, 14, 0], width: 5, advance: 5 },
    M: { rows: [0, 18, 30, 30, 18, 18, 18, 0], width: 5, advance: 5 },
    N: { rows: [0, 18, 26, 26, 22, 22, 18, 0], width: 5, advance: 5 },
    O: { rows: [0, 12, 18, 18, 18, 18, 12, 0], width: 5, advance: 5 },
    P: { rows: [0, 28, 18, 18, 28, 16, 16, 0], width: 5, advance: 5 },
    Q: { rows: [0, 12, 18, 18, 18, 18, 12, 6], width: 5, advance: 5 },
    R: { rows: [0, 28, 18, 18, 28, 18, 18, 0], width: 5, advance: 5 },
    S: { rows: [0, 14, 16, 12, 2, 2, 28, 0], width: 5, advance: 5 },
    T: { rows: [0, 31, 4, 4, 4, 4, 4, 0], width: 5, advance: 5 },
    U: { rows: [0, 18, 18, 18, 18, 18, 14, 0], width: 5, advance: 5 },
    V: { rows: [0, 18, 18, 18, 18, 12, 12, 0], width: 5, advance: 5 },
    W: { rows: [0, 18, 18, 18, 30, 30, 18, 0], width: 5, advance: 5 },
    X: { rows: [0, 18, 18, 12, 12, 18, 18, 0], width: 5, advance: 5 },
    Y: { rows: [0, 18, 18, 18, 14, 2, 28, 0], width: 5, advance: 5 },
    Z: { rows: [0, 30, 2, 4, 8, 16, 30, 0], width: 5, advance: 5 },
    "[": { rows: [14, 8, 8, 8, 8, 8, 8, 14], width: 5, advance: 5 },
    "\\": { rows: [16, 16, 8, 8, 4, 4, 2, 2], width: 5, advance: 5 },
    "]": { rows: [14, 2, 2, 2, 2, 2, 2, 14], width: 5, advance: 5 },
    "^": { rows: [0, 4, 10, 17, 0, 0, 0, 0], width: 5, advance: 5 },
    _: { rows: [0, 0, 0, 0, 0, 0, 0, 30], width: 5, advance: 5 },
    "`": { rows: [8, 4, 0, 0, 0, 0, 0, 0], width: 5, advance: 5 },
    a: { rows: [0, 0, 12, 2, 14, 18, 14, 0], width: 5, advance: 5 },
    b: { rows: [16, 16, 28, 18, 18, 18, 28, 0], width: 5, advance: 5 },
    c: { rows: [0, 0, 14, 16, 16, 16, 14, 0], width: 5, advance: 5 },
    d: { rows: [2, 2, 14, 18, 18, 18, 14, 0], width: 5, advance: 5 },
    e: { rows: [0, 0, 14, 18, 30, 16, 14, 0], width: 5, advance: 5 },
    f: { rows: [6, 8, 8, 28, 8, 8, 8, 0], width: 5, advance: 5 },
    g: { rows: [0, 0, 14, 18, 18, 12, 2, 28], width: 5, advance: 5 },
    h: { rows: [16, 16, 28, 18, 18, 18, 18, 0], width: 5, advance: 5 },
    i: { rows: [0, 4, 0, 12, 4, 4, 6, 0], width: 5, advance: 5 },
    j: { rows: [0, 4, 0, 4, 4, 4, 4, 24], width: 5, advance: 5 },
    k: { rows: [16, 16, 18, 20, 24, 20, 18, 0], width: 5, advance: 5 },
    l: { rows: [8, 8, 8, 8, 8, 8, 6, 0], width: 5, advance: 5 },
    m: { rows: [0, 0, 18, 30, 30, 18, 18, 0], width: 5, advance: 5 },
    n: { rows: [0, 0, 28, 18, 18, 18, 18, 0], width: 5, advance: 5 },
    o: { rows: [0, 0, 12, 18, 18, 18, 12, 0], width: 5, advance: 5 },
    p: { rows: [0, 0, 28, 18, 18, 28, 16, 16], width: 5, advance: 5 },
    q: { rows: [0, 0, 14, 18, 18, 14, 2, 2], width: 5, advance: 5 },
    r: { rows: [0, 0, 14, 18, 16, 16, 16, 0], width: 5, advance: 5 },
    s: { rows: [0, 0, 14, 16, 12, 2, 28, 0], width: 5, advance: 5 },
    t: { rows: [8, 8, 28, 8, 8, 8, 6, 0], width: 5, advance: 5 },
    u: { rows: [0, 0, 18, 18, 18, 18, 14, 0], width: 5, advance: 5 },
    v: { rows: [0, 0, 18, 18, 18, 12, 12, 0], width: 5, advance: 5 },
    w: { rows: [0, 0, 18, 18, 30, 30, 18, 0], width: 5, advance: 5 },
    x: { rows: [0, 0, 18, 12, 12, 18, 18, 0], width: 5, advance: 5 },
    y: { rows: [0, 0, 18, 18, 18, 14, 2, 28], width: 5, advance: 5 },
    z: { rows: [0, 0, 30, 2, 4, 8, 30, 0], width: 5, advance: 5 },
    "{": { rows: [6, 8, 8, 24, 24, 8, 8, 6], width: 5, advance: 5 },
    "|": { rows: [4, 4, 4, 4, 4, 4, 4, 4], width: 5, advance: 5 },
    "}": { rows: [24, 4, 4, 6, 6, 4, 4, 24], width: 5, advance: 5 },
    "~": { rows: [0, 0, 0, 9, 22, 0, 0, 0], width: 5, advance: 5 },
    "—": { rows: [0, 0, 0, 0, 31, 31, 0, 0], width: 5, advance: 5 },
    "•": { rows: [0, 0, 4, 14, 14, 4, 0, 0], width: 5, advance: 5 },
    "←": { rows: [0, 4, 8, 31, 8, 4, 0, 0], width: 5, advance: 5 },
    "→": { rows: [0, 4, 2, 31, 2, 4, 0, 0], width: 5, advance: 5 },
    "∀": { rows: [17, 17, 17, 31, 10, 10, 4, 0], width: 5, advance: 5 },
    "∅": { rows: [0, 2, 14, 22, 26, 28, 8, 0], width: 5, advance: 5 },
    "∵": { rows: [0, 10, 0, 0, 4, 0, 0, 0], width: 5, advance: 5 },
    "≺": { rows: [0, 2, 4, 8, 4, 2, 0, 0], width: 5, advance: 5 },
    "≻": { rows: [0, 8, 4, 2, 4, 8, 0, 0], width: 5, advance: 5 },
    "⊘": { rows: [14, 17, 19, 21, 25, 17, 14, 0], width: 5, advance: 5 },
    "─": { rows: [0, 0, 0, 31, 0, 0, 0, 0], width: 5, advance: 5 },
    "▰": { rows: [31, 31, 31, 31, 31, 31, 31, 31], width: 5, advance: 5 },
};

/** Visible, deterministic replacement for characters outside the generated atlas. */
export const MURAL_FONT_REPLACEMENT_GLYPH: MuralFontGlyph = {
    rows: [31, 17, 21, 17, 21, 17, 31, 0],
    width: 5,
    advance: 5,
};
