/// <reference types="bun-types" />

/**
 * Print the full `context.db` schema this plugin build creates.
 *
 * The Rust module writes the same domain tables and refuses to write when the
 * schema it finds is not the one it was built against, so its tests need the
 * real schema rather than a hand-copied subset. This dump is the shared source:
 * regenerate it after any migration that touches a domain table and commit the
 * result together with that migration.
 *
 *   bun scripts/dump-context-db-schema.ts > crates/mc-module/tests/fixtures/context-db-schema.sql
 */

import { Database } from "../packages/plugin/src/shared/sqlite";
import { runMigrations } from "../packages/plugin/src/features/magic-context/migrations";
import {
    initializeDatabase,
    LATEST_SUPPORTED_VERSION,
} from "../packages/plugin/src/features/magic-context/storage-db";

const db = new Database(":memory:");
initializeDatabase(db);
runMigrations(db);

// Replay order matters: a trigger or index cannot be created before its table.
// Shadow tables belonging to an fts5 virtual table are excluded — SQLite creates
// them itself and their names are the single-quoted form sqlite_master records.
const objects = db
    .prepare(
        `SELECT type, name, sql FROM sqlite_master
          WHERE sql IS NOT NULL AND sql NOT LIKE 'CREATE TABLE ''%'
            AND substr(name, 1, 7) != 'sqlite_'
          ORDER BY CASE type WHEN 'table' THEN 0 WHEN 'view' THEN 1 WHEN 'index' THEN 2 ELSE 3 END,
                   name ASC`,
    )
    .all() as Array<{ type: string; name: string; sql: string }>;

const persistedVersion = (
    db
        .prepare(
            "SELECT COALESCE(MAX(version), 0) AS version FROM schema_migrations WHERE version < 10000",
        )
        .get() as { version: number }
).version;

const lines: string[] = [
    `-- context.db schema snapshot: upstream migration lane v${persistedVersion}, plugin fence v${LATEST_SUPPORTED_VERSION}.`,
    "-- Generated by scripts/dump-context-db-schema.ts. Do not hand-edit.",
    "PRAGMA foreign_keys = OFF;",
];
for (const object of objects) {
    // sqlite_master stores the statement without its terminating semicolon.
    lines.push(`${object.sql};`);
}
for (let version = 1; version <= persistedVersion; version += 1) {
    lines.push(
        `INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (${version}, 'snapshot', 0);`,
    );
}

process.stdout.write(`${lines.join("\n")}\n`);
