export {
    buildCompartmentBlock,
    escapeXmlAttr,
    escapeXmlContent,
    getCompartments,
    getSessionFacts,
    replaceAllCompartmentState,
    replaceAllCompartmentStateAndBumpDepth,
    type SessionFact,
} from "./compartment-storage";
export {
    clearCompressionDepth,
    getAverageCompressionDepth,
    getMaxCompressionDepth,
    incrementCompressionDepth,
} from "./compression-depth-storage";
export {
    AUTHORITY_DOMAINS,
    type AuthorityDomain,
    type AuthorityManagedMarker,
    type AuthorityModuleClient,
    type AuthorityState,
    type AuthorityStatus,
    applyMirrorPage,
    type ChangefeedPage,
    type ChangefeedRow,
    ensureContextStoreUuid,
    getAuthorityManagedMarker,
    getContextStoreUuid,
    getMirrorCursor,
    installAuthorityManagedMarker,
    listAuthorityManagedMarkers,
    type PrepareAuthorityArgs,
    prepareAuthority,
    pullAndApplyMirrorPage,
    reconcileAuthorityMarker,
    removeAuthorityManagedMarker,
} from "./context-authority";
export {
    clearIndexedMessages,
    deleteIndexedMessage,
} from "./message-index";
export { runMigrations } from "./migrations";
export {
    computeProjectDocsHash,
    readProjectDocsCanonical,
} from "./project-docs-hash";
export {
    normalizeStoredProjectPath,
    ProjectIdentityError,
    type ProjectIdentityErrorClass,
    resolveProjectIdentity,
    resolveProjectIdentityStrict,
    storedPathBelongsToIdentity,
} from "./project-identity";
export {
    type CloneCompartmentRow,
    type CloneSessionStateFilter,
    type CloneTagRow,
    type CopySessionStateForCloneResult,
    copySessionStateForClone,
} from "./storage-clone";
export {
    applySqliteTuningPragmas,
    type ContextDatabase,
    closeDatabase,
    enforceSchemaFence,
    FORK_MIGRATION_VERSION_FLOOR,
    getDatabasePath,
    getDatabasePersistenceError,
    getPersistedSchemaVersion,
    initializeDatabase,
    isDatabasePersisted,
    LATEST_SUPPORTED_VERSION,
    type OpenDatabaseOptions,
    openDatabase,
    runSqliteOptimize,
    schemaVersionIsSupported,
    setSqlitePragmaConfig,
} from "./storage-db";
export {
    beginSynapseBatchLedger,
    type EmbeddingMeasurementInput,
    type EmbeddingMeasurementRow,
    finishSynapseBatchLedger,
    listEmbeddingMeasurements,
    normalizedQueryHash,
    recordEmbeddingMeasurement,
    type SynapseBatchLedgerInput,
} from "./storage-embedding-measurements";
export {
    deleteIdentityRekeyMap,
    getIdentityRekeyMap,
    type IdentityRekeyMapRow,
    listIdentityRekeyMaps,
    upsertIdentityRekeyMap,
} from "./storage-identity-rekey-map";
export {
    clearM0MutationsForSession,
    deleteM0Mutation,
    getM0Mutation,
    getM0MutationsAfterId,
    getM0MutationsBySession,
    getMaxM0MutationId,
    type M0MutationLogRow,
    type M0MutationType,
    queueM0Mutation,
    queueM0Mutation as appendM0Mutation,
} from "./storage-m0-mutation-log";
export {
    getMaxMemoryMutationId,
    getMaxMemoryMutationIdForProjects,
    getMemoryMutation,
    getMemoryMutationsForRender,
    getMemoryMutationsForRenderByProjects,
    MEMORY_VISIBILITY_MUTATION_CATEGORY,
    type MemoryMutationLogRow,
    type MemoryMutationType,
    queueMemoryMutation,
} from "./storage-memory-mutation-log";
export {
    type AcquireWrapupResult,
    type AppendAutoSearchHintOutcome,
    type AutoSearchHintDecision,
    acquireWrapupInProgress,
    addProcessedImageStrippedIds,
    addStaleReduceStrippedIds,
    advanceToolReclaimWatermark,
    appendAutoSearchHintDecision,
    appendNoteNudgeAnchor,
    applyStrippedPlaceholderDelta,
    armThinkingBindingRecovery,
    type Channel2NudgeState,
    captureChannel1PostReduceGraceBaseline,
    casChannel2NudgeClaim,
    casChannel2NudgeState,
    claimChannel2NudgeState,
    clearCachedM0,
    clearCachedM0M1,
    clearDetectedContextLimit,
    clearEmergencyDrainLatch,
    clearEmergencyRecovery,
    clearHistorianDrainFailure,
    clearHistorianFailureState,
    clearPendingCompactionMarkerStateIf,
    clearPendingPiCompactionMarkerStateIf,
    clearPersistedNoteNudge,
    clearPersistedReasoningWatermark,
    clearPersistedTodoSyntheticAnchor,
    clearSession,
    clearThinkingBindingRecoveryIf,
    DRAIN_WINDOW_MS,
    deliverNoteNudgeAtomic,
    describeProtectedTailDrainBudgetSkip,
    getAutoSearchHintDecisions,
    getChannel1NudgeState,
    getChannel2NudgeClaim,
    getChannel2NudgeClaimedAt,
    getChannel2NudgeState,
    getHiddenSeamPlaceholderIds,
    getHistorianFailureState,
    getLastNudgeUndropped,
    getNoteLastReadAt,
    getNoteNudgeAnchors,
    getOrCreateSessionMeta,
    getOverflowState,
    getPendingCompactionMarkerState,
    getPendingPiCompactionMarkerState,
    getPersistedNoteNudge,
    getPersistedReasoningWatermark,
    getPersistedTodoPermissionDenied,
    getPersistedTodoSyntheticAnchor,
    getProcessedImageStrippedIds,
    getSessionsWithPendingMarker,
    getSessionsWithPendingPiMarker,
    getSessionWorkMetrics,
    getStaleReduceStrippedIds,
    getStrippedPlaceholderIds,
    getThinkingBindingRecoveryTarget,
    getWrapupInProgressState,
    incrementHistorianFailure,
    isWrapupInProgress,
    loadPersistedUsage,
    loadProtectedTailMeta,
    MAX_STRIPPED_PLACEHOLDER_IDS,
    markChannel1PostReduceGracePending,
    markProtectedTailPolicyV3Seeded,
    markSessionCleanupPending,
    NEWEST_REASONING_BEARING_ASSISTANT,
    type PendingCompactionMarker,
    type PendingPiCompactionMarker,
    type PersistCachedM0Payload,
    type PersistedChannel1NudgeLevel,
    type PersistedChannel1NudgeState,
    type PersistedOverflowState,
    type PersistedTodoSyntheticAnchor,
    type PersistedUsageState,
    type ProtectedTailDrainBudgetState,
    type ProtectedTailDrainReservation,
    type ProtectedTailDrainReserveResult,
    type ProtectedTailMeta,
    type ProtectedTailSeedResult,
    persistCachedM0,
    protectedTailWindowBudget,
    pruneAutoSearchHintDecisions,
    pruneNoteNudgeAnchors,
    recordDetectedContextLimit,
    recordHistorianDrainFailure,
    recordOverflowDetected,
    recordProtectedTailNoEligibleHead,
    recordProtectedTailPublicationFloor,
    releaseWrapupInProgress,
    removeAutoSearchHintDecisionByMessageId,
    removeNoteNudgeAnchorByMessageId,
    removeStrippedPlaceholderId,
    reserveProtectedTailDrainTokens,
    resetLastNudgeCycle,
    resetLastNudgeCycleIfTailShrank,
    resetProtectedTailNoEligibleHead,
    retryPendingRustSessionCleanupsForProject,
    retryPendingSessionCleanups,
    rollbackProtectedTailDrainReservation,
    setChannel1NudgeState,
    setChannel2NudgeState,
    setLastNudgeUndropped,
    setNoteLastReadAt,
    setPendingCompactionMarkerState,
    setPendingPiCompactionMarkerState,
    setPersistedReasoningWatermark,
    setPersistedTodoPermissionDenied,
    setPersistedTodoSyntheticAnchor,
    setSessionWorkMetrics,
    setStrippedPlaceholderIds,
    updateSessionMeta,
    updateWrapupInProgress,
    WRAPUP_IN_PROGRESS_TTL_MS,
    type WrapupInProgressState,
} from "./storage-meta";
export { bumpSessionFactsVersion } from "./storage-meta-shared";
export {
    addNote,
    type ConditionCompileStatus,
    type DismissNoteOutcome,
    type DismissNoteResult,
    deleteNote,
    dismissNote,
    dismissNotes,
    getNotes,
    getPendingSmartNotes,
    getReadySmartNotes,
    getSessionNotes,
    getSmartNotes,
    markNoteChecked,
    markNoteReady,
    type Note,
    type NoteStatus,
    type NoteType,
    replaceAllSessionNotes,
    type UpdateNoteOptions,
    updateNote,
} from "./storage-notes";
export {
    clearPendingOps,
    getPendingOps,
    getPendingOpsCount,
    queuePendingOp,
    removePendingOp,
} from "./storage-ops";
export * from "./storage-primers";
export {
    bumpProjectMemoryEpoch,
    bumpProjectUserProfileVersion,
    deleteProjectState,
    ensureProjectState,
    GLOBAL_USER_PROFILE_PROJECT_PATH,
    getProjectState,
    type ProjectStateRow,
    setProjectState,
} from "./storage-project-state";
export {
    getSourceContents,
    replaceSourceContent,
    saveSourceContent,
} from "./storage-source";
export {
    getSubagentInvocations,
    getSubagentTotalsBySubagent,
    recordSubagentInvocation,
    type SubagentInvocationInput,
    type SubagentInvocationRow,
    type SubagentKind,
    type SubagentTotals,
} from "./storage-subagent-invocations";
export {
    type ActiveTagTokenAggregate,
    AGE_RECLAIM_MIN_TOKENS,
    type AgeReclaimToolTag,
    adoptFallbackTagMessageId,
    adoptPiFallbackMessageTag,
    adoptPiFallbackToolOwnerTag,
    deleteTagsByMessageId,
    deriveTagLoadFloor,
    findAdoptableFallbackTags,
    findPiFallbackToolOwnerTags,
    getActiveTagsBySession,
    getActiveTagTokenAggregate,
    getActiveTagTokenTotalsByMessage,
    getActiveToolTagsForAgeReclaim,
    getAllStatusTagTokenTotalsFlat,
    getDroppedTagsByNumbers,
    getMaxDroppedTagNumber,
    getMaxTagNumberBySession,
    getMinMessageTagNumberForRawId,
    getOldestActiveUnprotectedToolTags,
    getPersistedToolTagAccounting,
    getTagById,
    getTagsByNumbers,
    getTagsBySession,
    getTagsForPendingOperations,
    getTopNBySize,
    getTriggerTagTokenUpperBound,
    hasPiFallbackMessageTags,
    hasPiFallbackToolOwnerTags,
    insertTag,
    type MessageTokenTotal,
    markTagsCompactedByMessageIds,
    type ToolReclaimHintTag,
    updateCavemanDepth,
    updateTagDropMode,
    updateTagMessageId,
    updateTagStatus,
} from "./storage-tags";
export {
    clearV22BackfillFailures,
    deleteV22BackfillFailure,
    getV22BackfillFailure,
    listV22BackfillFailures,
    recordV22BackfillFailure,
    type V22BackfillErrorClass,
    type V22BackfillFailureRow,
} from "./storage-v22-backfill-failures";
export {
    bumpEpochsForWorkspaceMemberSet,
    bumpEpochsForWorkspaceMembers,
    computeWorkspaceEpochFingerprint,
    type ExpandedWorkspaceIdentitySet,
    expandWorkspaceIdentitySet,
    expandWorkspaceIdentitySetWithAliases,
    resolveStoredPathWorkspaceIdentity,
    resolveWorkspaceIdentitySet,
    sourceNameForMemory,
    storedPathBelongsToWorkspace,
    type WorkspaceIdentitySet,
} from "./workspaces";
