-- context.db schema snapshot: upstream migration lane v91, plugin fence v91.
-- Generated by scripts/dump-context-db-schema.ts. Do not hand-edit.
PRAGMA foreign_keys = OFF;
CREATE TABLE authority_capture_bounds (
                    project_path TEXT NOT NULL,
                    domain TEXT NOT NULL CHECK(domain IN ('memories', 'notes')),
                    max_rowid INTEGER NOT NULL,
                    data_version INTEGER NOT NULL,
                    captured_at INTEGER NOT NULL, mutation_epoch INTEGER NOT NULL DEFAULT 0,
                    PRIMARY KEY(project_path, domain)
                );
CREATE TABLE authority_managed (
                    project_path TEXT PRIMARY KEY,
                    context_store_uuid TEXT NOT NULL,
                    marked_at INTEGER NOT NULL
                );
CREATE TABLE authority_repair_pending (
                    project_path TEXT PRIMARY KEY,
                    started_at INTEGER NOT NULL
                );
CREATE TABLE "compartment_chunk_embeddings" (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        compartment_id INTEGER NOT NULL REFERENCES compartments(id) ON DELETE CASCADE,
                        session_id TEXT NOT NULL,
                        project_path TEXT NOT NULL,
                        harness TEXT NOT NULL DEFAULT 'opencode',
                        window_index INTEGER NOT NULL DEFAULT 0,
                        start_ordinal INTEGER NOT NULL,
                        end_ordinal INTEGER NOT NULL,
                        chunk_hash TEXT NOT NULL,
                        model_id TEXT NOT NULL,
                        dims INTEGER NOT NULL,
                        vector BLOB NOT NULL,
                        created_at INTEGER NOT NULL,
                        UNIQUE(compartment_id, model_id, window_index)
                    );
CREATE TABLE compartment_events (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      session_id TEXT NOT NULL,
      compartment_id INTEGER,
      kind TEXT NOT NULL,
      at_compartment INTEGER,
      fields_json TEXT NOT NULL DEFAULT '{}',
      created_at INTEGER NOT NULL, -- epoch ms (Date.now())
      harness TEXT NOT NULL DEFAULT 'opencode'
    );
CREATE TABLE compartment_state_lease (
      session_id TEXT PRIMARY KEY NOT NULL,
      holder_id TEXT NOT NULL,
      owner_pid INTEGER,
      acquired_at INTEGER NOT NULL,
      expires_at INTEGER NOT NULL
    );
CREATE TABLE compartments (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      session_id TEXT NOT NULL,
      sequence INTEGER NOT NULL,
      start_message INTEGER NOT NULL,
      end_message INTEGER NOT NULL,
      start_message_id TEXT DEFAULT '',
      end_message_id TEXT DEFAULT '',
      title TEXT NOT NULL,
      content TEXT NOT NULL,
      p1 TEXT,
      p2 TEXT,
      p3 TEXT,
      p4 TEXT,
      importance INTEGER NOT NULL DEFAULT 50,
      episode_type TEXT,
      p1_embedding BLOB,
      p1_embedding_model_id TEXT,
      legacy INTEGER NOT NULL DEFAULT 0,
      created_at INTEGER NOT NULL, -- epoch ms (Date.now())
      harness TEXT NOT NULL DEFAULT 'opencode', rebase_status TEXT NOT NULL DEFAULT 'ok',
      UNIQUE(session_id, sequence)
    );
CREATE TABLE compression_depth (
      session_id TEXT NOT NULL,
      message_ordinal INTEGER NOT NULL,
      depth INTEGER NOT NULL DEFAULT 0,
      harness TEXT NOT NULL DEFAULT 'opencode',
      PRIMARY KEY(session_id, message_ordinal)
    );
CREATE TABLE context_privilege_state (
                    id INTEGER PRIMARY KEY CHECK(id = 1),
                    enabled INTEGER NOT NULL DEFAULT 0 CHECK(enabled IN (0, 1))
                );
CREATE TABLE context_store_meta (
                    key TEXT PRIMARY KEY,
                    value TEXT NOT NULL
                );
CREATE TABLE domain_mutation_epoch (
                    project_path TEXT NOT NULL,
                    domain TEXT NOT NULL CHECK(domain IN ('memories', 'notes')),
                    epoch INTEGER NOT NULL DEFAULT 0,
                    PRIMARY KEY(project_path, domain)
                );
CREATE TABLE dream_queue (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      project_path TEXT NOT NULL,
      reason TEXT NOT NULL,
      enqueued_at INTEGER NOT NULL,
      started_at INTEGER,
      retry_count INTEGER DEFAULT 0
    );
CREATE TABLE dream_runs (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      project_path TEXT NOT NULL,
      started_at INTEGER NOT NULL,
      finished_at INTEGER NOT NULL,
      holder_id TEXT NOT NULL,
      tasks_json TEXT NOT NULL,
      tasks_succeeded INTEGER NOT NULL DEFAULT 0,
      tasks_failed INTEGER NOT NULL DEFAULT 0,
      smart_notes_surfaced INTEGER NOT NULL DEFAULT 0,
      smart_notes_pending INTEGER NOT NULL DEFAULT 0,
      memory_changes_json TEXT,
      parent_session_id TEXT
    );
CREATE TABLE dream_state (
      key TEXT PRIMARY KEY,
      value TEXT NOT NULL
    );
CREATE TABLE embedding_identity_active (
      project_path TEXT NOT NULL,
      scope TEXT NOT NULL CHECK(scope IN ('memory', 'commit', 'chunk')),
      model_id TEXT NOT NULL,
      last_active_at INTEGER NOT NULL,
      PRIMARY KEY(project_path, scope, model_id)
    );
CREATE TABLE embedding_measurement_corpus (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      session_id TEXT NOT NULL,
      project_path TEXT NOT NULL DEFAULT '',
      dedup_key TEXT NOT NULL DEFAULT '',
      cohort_key TEXT NOT NULL DEFAULT '',
      query_text_hash TEXT NOT NULL DEFAULT '',
      primary_result_ids_json TEXT NOT NULL DEFAULT '[]',
      shadow_result_ids_json TEXT NOT NULL DEFAULT '[]',
      primary_latency_ms INTEGER,
      shadow_latency_ms INTEGER,
      primary_failed INTEGER NOT NULL DEFAULT 0,
      shadow_failed INTEGER NOT NULL DEFAULT 0,
      primary_model_id TEXT NOT NULL DEFAULT '',
      shadow_model_id TEXT NOT NULL DEFAULT '',
      primary_fingerprint TEXT NOT NULL DEFAULT '',
      shadow_fingerprint TEXT NOT NULL DEFAULT '',
      primary_epoch INTEGER NOT NULL DEFAULT 0,
      shadow_epoch INTEGER NOT NULL DEFAULT 0,
      corpus_hash TEXT NOT NULL DEFAULT '',
      coverage_json TEXT NOT NULL DEFAULT '{}',
      created_at INTEGER NOT NULL DEFAULT 0, -- epoch ms (Date.now())
      UNIQUE(dedup_key, cohort_key)
    );
CREATE TABLE embedding_registrations (
      project_path TEXT PRIMARY KEY,
      provider_identity TEXT NOT NULL DEFAULT '',
      model_id TEXT NOT NULL DEFAULT '',
      chunk_model_id TEXT NOT NULL DEFAULT '',
      fingerprint TEXT NOT NULL DEFAULT '',
      table_epoch INTEGER NOT NULL DEFAULT 0,
      dims INTEGER NOT NULL DEFAULT 0,
      provenance_json TEXT NOT NULL DEFAULT '{}',
      generation INTEGER NOT NULL DEFAULT 0,
      updated_at INTEGER NOT NULL DEFAULT 0
    );
CREATE TABLE "git_commit_embeddings" (
                        sha TEXT NOT NULL,
                        embedding BLOB NOT NULL,
                        model_id TEXT NOT NULL,
                        created_at INTEGER NOT NULL,
                        PRIMARY KEY(sha, model_id),
                        FOREIGN KEY(sha) REFERENCES git_commits(sha) ON DELETE CASCADE
                    );
CREATE TABLE git_commits (
                    sha TEXT PRIMARY KEY,
                    project_path TEXT NOT NULL,
                    short_sha TEXT NOT NULL,
                    message TEXT NOT NULL,
                    author TEXT,
                    committed_at INTEGER NOT NULL,
                    indexed_at INTEGER NOT NULL
                );
CREATE VIRTUAL TABLE git_commits_fts USING fts5(
                    sha UNINDEXED,
                    project_path UNINDEXED,
                    message,
                    tokenize = 'porter unicode61'
                );
CREATE TABLE git_sweep_coordinator (
      project_path TEXT PRIMARY KEY,
      lease_holder TEXT,
      lease_expires_at INTEGER,
      last_swept_at INTEGER
    );
CREATE TABLE historian_runs (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      session_id TEXT NOT NULL,
      harness TEXT NOT NULL DEFAULT 'opencode',
      subagent_invocation_id INTEGER,
      run_kind TEXT NOT NULL,
      status TEXT NOT NULL,
      failure_reason TEXT,
      chunk_start_ordinal INTEGER,
      chunk_end_ordinal INTEGER,
      unprocessed_from INTEGER,
      compartments_produced INTEGER NOT NULL DEFAULT 0,
      compartment_id_min INTEGER,
      compartment_id_max INTEGER,
      facts_emitted INTEGER NOT NULL DEFAULT 0,
      facts_by_category_json TEXT,
      events_emitted INTEGER NOT NULL DEFAULT 0,
      importance_min INTEGER,
      importance_max INTEGER,
      importance_avg REAL,
      discarded_last INTEGER NOT NULL DEFAULT 0,
      legacy INTEGER NOT NULL DEFAULT 0,
      created_at INTEGER NOT NULL -- epoch ms (Date.now())
    );
CREATE TABLE identity_merge_log (
         id INTEGER PRIMARY KEY AUTOINCREMENT,
         from_identity TEXT NOT NULL,
         to_identity TEXT NOT NULL,
         table_name TEXT NOT NULL,
         row_id TEXT NOT NULL,
         action TEXT NOT NULL,
         target_row_id TEXT,
         merged_at INTEGER NOT NULL
       );
CREATE TABLE lkg_slots (
                    session_id TEXT PRIMARY KEY,
                    json_prefix TEXT NOT NULL,
                    input_id_seq TEXT NOT NULL,
                    input_content_digests TEXT NOT NULL,
                    input_content_signatures TEXT,
                    last_input_message_id TEXT NOT NULL,
                    model_key TEXT,
                    provider_key TEXT,
                    captured_at INTEGER NOT NULL,
                    row_version INTEGER,
                    capture_sequence INTEGER
                );
CREATE TABLE m0_mutation_log (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      session_id TEXT NOT NULL,
      mutation_type TEXT NOT NULL CHECK (mutation_type IN (
        'compartment_delete', 'compartment_merge', 'recomp_boundary_change', 'compartment_upgrade'
      )),
      target_id INTEGER,
      queued_at INTEGER NOT NULL
    );
CREATE TABLE memories (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      project_path TEXT NOT NULL,
      category TEXT NOT NULL,
      content TEXT NOT NULL,
      normalized_hash TEXT NOT NULL,
      importance INTEGER,
      scope TEXT NOT NULL DEFAULT 'project',
      shareable INTEGER NOT NULL DEFAULT 0,
      source_session_id TEXT,
      source_type TEXT DEFAULT 'historian',
      seen_count INTEGER DEFAULT 1,
      retrieval_count INTEGER DEFAULT 0,
      first_seen_at INTEGER NOT NULL,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      last_seen_at INTEGER NOT NULL,
      last_retrieved_at INTEGER,
      status TEXT DEFAULT 'active',
      expires_at INTEGER,
      verification_status TEXT DEFAULT 'unverified',
      verified_at INTEGER,
      classified_at INTEGER,
      superseded_by_memory_id INTEGER,
      merged_from TEXT,
      metadata_json TEXT,
      mural_cue TEXT,
      mural_cue_hash TEXT,
      mural_cue_at INTEGER,
      mural_cue_rejection_count INTEGER NOT NULL DEFAULT 0,
      UNIQUE(project_path, category, normalized_hash)
    );
CREATE VIRTUAL TABLE memories_fts USING fts5(
      content,
      category,
      content='memories',
      content_rowid='id',
      tokenize='porter unicode61'
    );
CREATE TABLE memory_embedding_watermarks (
      project_path TEXT PRIMARY KEY,
      written_memory_id INTEGER NOT NULL DEFAULT 0,
      embedded_memory_id INTEGER NOT NULL DEFAULT 0,
      updated_at INTEGER NOT NULL DEFAULT 0
    );
CREATE TABLE "memory_embeddings" (
                        memory_id INTEGER NOT NULL REFERENCES memories(id) ON DELETE CASCADE,
                        embedding BLOB NOT NULL,
                        model_id TEXT NOT NULL,
                        PRIMARY KEY(memory_id, model_id)
                    );
CREATE TABLE memory_mutation_log (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      project_path TEXT NOT NULL,
      mutation_type TEXT NOT NULL CHECK (mutation_type IN ('archive', 'delete', 'update', 'superseded')),
      target_memory_id INTEGER NOT NULL,
      superseded_by_id INTEGER,
      category TEXT,
      new_content TEXT,
      queued_at INTEGER NOT NULL
    );
CREATE TABLE memory_verifications (
      memory_id    INTEGER NOT NULL REFERENCES memories(id) ON DELETE CASCADE,
      file_path    TEXT NOT NULL,
      -- verified_at=0 means "mapped (files known) but not yet content-verified".
      -- map-memories sets mapped_at + verified_at=0; verify sets verified_at=now.
      verified_at  INTEGER NOT NULL,
       mapped_at    INTEGER NOT NULL DEFAULT 0,
       -- Distinguishes mapper-authored independence from a host rejection fallback.
       mapping_origin TEXT NOT NULL DEFAULT 'mapper',
       PRIMARY KEY (memory_id, file_path)
    );
CREATE TABLE message_fts_rowid_map (
      session_id TEXT NOT NULL,
      message_ordinal INTEGER NOT NULL,
      fts_rowid INTEGER NOT NULL,
      message_time_ms INTEGER,
      PRIMARY KEY(session_id, message_ordinal)
    );
CREATE TABLE message_fts_rowid_map_backfill_state (
      id INTEGER PRIMARY KEY CHECK(id = 1),
      watermark_rowid INTEGER NOT NULL DEFAULT 0,
      completed INTEGER NOT NULL DEFAULT 0 CHECK(completed IN (0, 1)),
      updated_at INTEGER NOT NULL DEFAULT 0
    );
CREATE VIRTUAL TABLE message_history_fts USING fts5(
      session_id UNINDEXED,
      message_ordinal UNINDEXED,
      message_id UNINDEXED,
      role,
      content,
      tokenize='porter unicode61'
    );
CREATE TABLE message_history_index (
      session_id TEXT PRIMARY KEY,
      last_indexed_ordinal INTEGER NOT NULL DEFAULT 0,
      dirty_floor_ordinal INTEGER NOT NULL DEFAULT 0,
      updated_at INTEGER NOT NULL,
      harness TEXT NOT NULL DEFAULT 'opencode'
    );
CREATE TABLE message_history_orphan_sweep (
      harness TEXT PRIMARY KEY,
      cursor_session_id TEXT NOT NULL DEFAULT '',
      last_swept_at INTEGER
    );
CREATE TABLE message_history_source (
      session_id TEXT NOT NULL,
      message_id TEXT NOT NULL,
      message_ordinal INTEGER NOT NULL,
      source_version TEXT NOT NULL,
      normalized_content_hash TEXT NOT NULL,
      role TEXT NOT NULL,
      harness TEXT NOT NULL DEFAULT 'opencode',
      updated_at INTEGER NOT NULL,
      PRIMARY KEY(session_id, message_id)
    );
CREATE TABLE message_time_backfill_state (
      id INTEGER PRIMARY KEY CHECK(id = 1),
      cursor_session_id TEXT NOT NULL DEFAULT '',
      cursor_ordinal INTEGER NOT NULL DEFAULT 0,
      completed INTEGER NOT NULL DEFAULT 0 CHECK(completed IN (0, 1)),
      updated_at INTEGER NOT NULL DEFAULT 0
    );
CREATE TABLE migration_pending (
                    migration_key TEXT PRIMARY KEY,
                    source_session_id TEXT NOT NULL,
                    target_harness TEXT NOT NULL,
                    pi_session_id TEXT NOT NULL,
                    final_path TEXT NOT NULL,
                    stage_path TEXT NOT NULL,
                    content_sha256 TEXT NOT NULL,
                    phase TEXT NOT NULL CHECK (phase IN ('staged', 'db_committed')),
                    created_at INTEGER NOT NULL
                );
CREATE TABLE mirror_cursors (
                    domain TEXT PRIMARY KEY CHECK(domain IN ('memories', 'notes')),
                    cursor INTEGER NOT NULL DEFAULT 0,
                    updated_at INTEGER NOT NULL DEFAULT 0
                );
CREATE TABLE mirror_identity (
                    domain TEXT NOT NULL CHECK(domain IN ('memories', 'notes')),
                    module_project TEXT NOT NULL,
                    module_row_id INTEGER NOT NULL,
                    context_row_id INTEGER NOT NULL,
                    PRIMARY KEY(domain, module_project, module_row_id),
                    UNIQUE(domain, context_row_id)
                );
CREATE TABLE mirror_live_memory_rows (
                    module_project TEXT NOT NULL,
                    module_row_id INTEGER NOT NULL,
                    category TEXT NOT NULL,
                    normalized_hash TEXT NOT NULL, full_row_snapshot TEXT,
                    PRIMARY KEY(module_project, module_row_id)
                );
CREATE TABLE mirror_live_staging (
                    generation TEXT NOT NULL,
                    module_project TEXT NOT NULL,
                    module_row_id INTEGER NOT NULL,
                    category TEXT NOT NULL,
                    normalized_hash TEXT NOT NULL, full_row_snapshot TEXT,
                    PRIMARY KEY(generation, module_project, module_row_id)
                );
CREATE TABLE mirror_note_revisions (
                    module_project TEXT NOT NULL,
                    module_row_id INTEGER NOT NULL,
                    context_row_id INTEGER NOT NULL,
                    status_version INTEGER NOT NULL DEFAULT 0,
                    PRIMARY KEY(module_project, module_row_id),
                    UNIQUE(context_row_id)
                );
CREATE TABLE mirror_pending_references (
                    domain TEXT NOT NULL CHECK(domain = 'memories'),
                    module_project TEXT NOT NULL,
                    module_row_id INTEGER NOT NULL,
                    target_module_row_id INTEGER NOT NULL,
                    PRIMARY KEY(domain, module_project, module_row_id)
                );
CREATE TABLE mirror_resnapshot_state (
                    domain TEXT PRIMARY KEY CHECK(domain = 'memories'),
                    status TEXT NOT NULL CHECK(status IN ('pending_check', 'resnapshotting', 'complete')),
                    updated_at INTEGER NOT NULL
                , generation TEXT);
CREATE TABLE mural_manifest (
                    project_path TEXT PRIMARY KEY,
                    image BLOB NOT NULL,
                    content_hash TEXT NOT NULL,
                    rendered_at INTEGER NOT NULL,
                    model TEXT,
                    memory_ids_json TEXT NOT NULL DEFAULT '[]',
                    width INTEGER NOT NULL DEFAULT 1092,
                    height INTEGER NOT NULL DEFAULT 1092
                );
CREATE TABLE notes (
					id INTEGER PRIMARY KEY AUTOINCREMENT,
					type TEXT NOT NULL DEFAULT 'session',
					status TEXT NOT NULL DEFAULT 'active',
					content TEXT NOT NULL,
					session_id TEXT,
					project_path TEXT,
					surface_condition TEXT,
					created_at INTEGER NOT NULL,
					updated_at INTEGER NOT NULL,
					last_checked_at INTEGER,
					ready_at INTEGER,
					ready_reason TEXT,
					compiled_provider TEXT,
					compiled_config TEXT,
					compiled_at INTEGER,
					compile_status TEXT CHECK(compile_status IN ('compiled', 'plain', 'refused'))
				, harness TEXT NOT NULL DEFAULT 'opencode', anchor_ordinal INTEGER, compiled_check TEXT, manifest_json TEXT, check_hash TEXT, check_cron TEXT, check_version INTEGER NOT NULL DEFAULT 0, check_status TEXT NOT NULL DEFAULT 'uncompiled', check_failure_count INTEGER NOT NULL DEFAULT 0, check_network_failure_count INTEGER NOT NULL DEFAULT 0, check_quarantined_until INTEGER, check_next_due_at INTEGER, check_compiled_at INTEGER, check_false_since_at INTEGER, check_last_liveness_at INTEGER, policy_version INTEGER NOT NULL DEFAULT 1, anchor_block_id TEXT);
CREATE TABLE pending_ops (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      session_id TEXT,
      tag_id INTEGER,
      operation TEXT,
      queued_at INTEGER,
      harness TEXT NOT NULL DEFAULT 'opencode'
    );
CREATE TABLE pending_session_cleanup (
      session_id TEXT PRIMARY KEY,
      harness TEXT NOT NULL DEFAULT 'opencode',
      requested_at INTEGER NOT NULL,
      last_attempt_at INTEGER
    );
CREATE TABLE plugin_messages (
					id INTEGER PRIMARY KEY AUTOINCREMENT,
					direction TEXT NOT NULL,
					type TEXT NOT NULL,
					payload TEXT NOT NULL DEFAULT '{}',
					session_id TEXT,
					created_at INTEGER NOT NULL,
					consumed_at INTEGER
				);
CREATE TABLE primer_candidates (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      project_path TEXT NOT NULL,
      harness TEXT NOT NULL DEFAULT 'opencode',
      session_id TEXT NOT NULL,
      question TEXT NOT NULL,
      normalized_question TEXT NOT NULL,
      source_compartment_start INTEGER,
      source_compartment_end INTEGER,
      source_start_message_id TEXT NOT NULL DEFAULT '',
      source_end_message_id TEXT NOT NULL DEFAULT '',
      source_message_time INTEGER NOT NULL,
      question_embedding BLOB,
      question_embedding_model_id TEXT,
      created_at INTEGER NOT NULL, -- epoch ms (Date.now())
      UNIQUE(project_path, harness, session_id, source_start_message_id, source_end_message_id)
    );
CREATE TABLE primers (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      project_path TEXT NOT NULL,
      question TEXT NOT NULL,
      question_embedding BLOB,
      question_embedding_model_id TEXT,
      answer TEXT NOT NULL DEFAULT '',
      status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active', 'archived')),
      total_support INTEGER NOT NULL DEFAULT 0,
      last_observed_at INTEGER,
      answer_refreshed_at INTEGER,
      source_candidate_ids TEXT NOT NULL DEFAULT '[]',
      source_candidate_provenance TEXT,
      created_at INTEGER NOT NULL, -- epoch ms (Date.now())
      updated_at INTEGER NOT NULL
    );
CREATE VIRTUAL TABLE primers_fts USING fts5(
      question,
      answer,
      project_path UNINDEXED,
      content='primers',
      content_rowid='id',
      tokenize='porter unicode61'
    );
CREATE TABLE project_key_files (
      project_path           TEXT    NOT NULL,
      path                   TEXT    NOT NULL,
      content                TEXT    NOT NULL,
      content_hash           TEXT    NOT NULL,
      local_token_estimate   INTEGER NOT NULL,
      generated_at           INTEGER NOT NULL,
      generated_by_model     TEXT,
      generation_config_hash TEXT    NOT NULL,
      stale_reason           TEXT,
      PRIMARY KEY (project_path, path)
    );
CREATE TABLE project_key_files_version (
      project_path TEXT    PRIMARY KEY,
      version      INTEGER NOT NULL DEFAULT 0
    );
CREATE TABLE project_state (
      project_path TEXT PRIMARY KEY,
      project_memory_epoch INTEGER NOT NULL DEFAULT 0,
      project_user_profile_version INTEGER NOT NULL DEFAULT 0,
      updated_at INTEGER NOT NULL DEFAULT 0
    );
CREATE TABLE recomp_compartments (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      session_id TEXT NOT NULL,
      sequence INTEGER NOT NULL,
      start_message INTEGER NOT NULL,
      end_message INTEGER NOT NULL,
      start_message_id TEXT DEFAULT '',
      end_message_id TEXT DEFAULT '',
      title TEXT NOT NULL,
      content TEXT NOT NULL,
      p1 TEXT,
      p2 TEXT,
      p3 TEXT,
      p4 TEXT,
      importance INTEGER NOT NULL DEFAULT 50,
      episode_type TEXT,
      pass_number INTEGER NOT NULL,
      created_at INTEGER NOT NULL, -- epoch ms (Date.now())
      harness TEXT NOT NULL DEFAULT 'opencode', rebase_status TEXT NOT NULL DEFAULT 'ok',
      UNIQUE(session_id, sequence)
    );
CREATE TABLE recomp_facts (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      session_id TEXT NOT NULL,
      category TEXT NOT NULL,
      content TEXT NOT NULL,
      pass_number INTEGER NOT NULL,
      created_at INTEGER NOT NULL, -- epoch ms (Date.now())
      harness TEXT NOT NULL DEFAULT 'opencode'
    );
CREATE TABLE retrospective_processed_windows (
      project_path TEXT NOT NULL,
      window_key   TEXT NOT NULL,
      processed_at INTEGER NOT NULL,
      PRIMARY KEY (project_path, window_key)
    );
CREATE TABLE schema_migrations (
			version INTEGER PRIMARY KEY,
			description TEXT NOT NULL,
			applied_at INTEGER NOT NULL
		);
CREATE TABLE schema_migrations_meta (
      key   TEXT PRIMARY KEY,
      value TEXT NOT NULL
    );
CREATE TABLE session_facts (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      session_id TEXT NOT NULL,
      category TEXT NOT NULL,
      content TEXT NOT NULL,
      created_at INTEGER NOT NULL, -- epoch ms (Date.now())
      updated_at INTEGER NOT NULL,
      harness TEXT NOT NULL DEFAULT 'opencode'
    );
CREATE TABLE session_meta (
      session_id TEXT PRIMARY KEY,
      harness TEXT NOT NULL DEFAULT 'opencode',
      last_response_time INTEGER,
      cache_ttl TEXT,
      counter INTEGER DEFAULT 0,
      tags_version INTEGER NOT NULL DEFAULT 0,
      last_nudge_tokens INTEGER DEFAULT 0,
      last_nudge_band TEXT DEFAULT '',
      last_nudge_undropped INTEGER DEFAULT 0,
      last_nudge_level TEXT DEFAULT '',
      channel2_nudge_state TEXT DEFAULT '',
      channel2_nudge_claimed_at INTEGER DEFAULT 0,
      channel2_nudge_claim_token TEXT DEFAULT '',
      last_emergency_input_sample INTEGER DEFAULT 0,
      last_transform_error TEXT DEFAULT '',
      nudge_anchor_message_id TEXT DEFAULT '',
      nudge_anchor_text TEXT DEFAULT '',
      sticky_turn_reminder_text TEXT DEFAULT '',
      sticky_turn_reminder_message_id TEXT DEFAULT '',
      note_nudge_trigger_pending INTEGER DEFAULT 0,
      note_nudge_trigger_message_id TEXT DEFAULT '',
      note_nudge_sticky_text TEXT DEFAULT '',
      note_nudge_sticky_message_id TEXT DEFAULT '',
      note_nudge_anchors TEXT NOT NULL DEFAULT '[]',
      auto_search_hint_decisions TEXT NOT NULL DEFAULT '[]',
      last_todo_state TEXT DEFAULT '',
      todo_permission_denied INTEGER NOT NULL DEFAULT 2,
      todo_synthetic_call_id TEXT DEFAULT '',
      todo_synthetic_anchor_message_id TEXT DEFAULT '',
      todo_synthetic_state_json TEXT DEFAULT '',
      is_subagent INTEGER DEFAULT 0,
      last_context_percentage REAL DEFAULT 0,
      last_input_tokens INTEGER DEFAULT 0,
      detected_context_limit_provenance TEXT NOT NULL DEFAULT 'unknown',
      observed_safe_input_tokens INTEGER NOT NULL DEFAULT 0,
      cache_alert_sent INTEGER NOT NULL DEFAULT 0,
      times_execute_threshold_reached INTEGER DEFAULT 0,
      compartment_in_progress INTEGER DEFAULT 0,
      historian_failure_count INTEGER DEFAULT 0,
      historian_last_error TEXT DEFAULT NULL,
      historian_last_failure_at INTEGER DEFAULT NULL,
      system_prompt_hash TEXT DEFAULT '',
      memory_block_cache TEXT DEFAULT '',
      memory_block_count INTEGER DEFAULT 0,
      memory_block_ids TEXT DEFAULT '',
      -- pending_compaction_marker_state: intentionally NULLABLE without a
      -- default. Absence of a deferred marker is SQL NULL; presence is a
      -- valid JSON blob written via setPendingCompactionMarkerState.
      -- Excluded from the healAllNullColumns fallback list. Readers filter
      -- IS NOT NULL AND != empty-string defensively. Plan v6 section 3.
      pending_compaction_marker_state TEXT,
      -- Target OpenCode message id used to inject the current compaction marker.
      -- Nullable for legacy persisted markers; repaired on the next marker move.
      compaction_marker_target_end_message_id TEXT,
      -- pending_pi_compaction_marker_state: intentionally NULLABLE without a
      -- default. Absence of a deferred Pi-native marker is SQL NULL; presence
      -- is a valid JSON blob written via setPendingPiCompactionMarkerState.
      -- Excluded from the healAllNullColumns fallback list.
      pending_pi_compaction_marker_state TEXT,
      new_work_tokens INTEGER NOT NULL DEFAULT 0,
      total_input_tokens INTEGER NOT NULL DEFAULT 0,
      -- Retired columns remain in place so existing databases keep the same schema:
      -- deferred_execute_state was used by the removed turn-boundary execute hold.
      deferred_execute_state TEXT,
      cached_m0_bytes BLOB,
      cached_m0_project_memory_epoch INTEGER,
      cached_m0_workspace_fingerprint TEXT,
      cached_m0_project_user_profile_version INTEGER,
      cached_m0_max_compartment_seq INTEGER,
      cached_m0_max_memory_id INTEGER,
      cached_m0_max_mutation_id INTEGER,
      cached_m0_max_memory_mutation_id INTEGER,
      cached_m0_project_docs_hash TEXT,
      cached_m1_bytes BLOB,
      last_observed_model_key TEXT,
      last_usage_context_limit INTEGER NOT NULL DEFAULT 0,
      prior_boundary_ordinal INTEGER NOT NULL DEFAULT 1,
      protected_tokens_effective INTEGER,
      protected_tokens_pre_snapshot TEXT,
      protected_tail_policy_version INTEGER NOT NULL DEFAULT 0,
      protected_tail_drain_window_started_at INTEGER NOT NULL DEFAULT 0,
      protected_tail_drain_tokens INTEGER NOT NULL DEFAULT 0,
      recovery_no_eligible_head_count INTEGER NOT NULL DEFAULT 0,
      force_emergency_bypass_window_start INTEGER NOT NULL DEFAULT 0,
      force_emergency_bypass_used INTEGER NOT NULL DEFAULT 0,
      emergency_drain_active INTEGER NOT NULL DEFAULT 0,
      historian_drain_failure_at INTEGER NOT NULL DEFAULT 0,
      wrapup_in_progress_state TEXT,
      compaction_mode_record TEXT,
      cached_m0_materialized_at INTEGER,
      cached_m0_session_facts_version INTEGER,
      cached_m0_upgrade_state TEXT,
      cached_m0_system_hash TEXT,
      cached_m0_tool_set_hash TEXT,
      cached_m0_model_key TEXT,
       cached_m0_project_identity TEXT,
       cached_m0_last_baseline_end_message_id TEXT,
       thinking_binding_recovery_target TEXT NOT NULL DEFAULT '',
       upgrade_reminded_at INTEGER,
       pi_stable_id_scheme INTEGER
    , note_last_read_at INTEGER DEFAULT 0, cleared_reasoning_through_tag INTEGER DEFAULT 0, tool_reclaim_watermark INTEGER DEFAULT 0, stripped_placeholder_ids TEXT DEFAULT '', stale_reduce_stripped_ids TEXT DEFAULT '', processed_image_stripped_ids TEXT DEFAULT '', merged_reasoning_stripped_ids TEXT DEFAULT '', trailing_blank_decisions TEXT DEFAULT '', system_prompt_tokens INTEGER DEFAULT 0, compaction_marker_state TEXT DEFAULT '', key_files TEXT DEFAULT '', conversation_tokens INTEGER DEFAULT 0, tool_call_tokens INTEGER DEFAULT 0, recomp_partial_range_start INTEGER DEFAULT 0, recomp_partial_range_end INTEGER DEFAULT 0, detected_context_limit INTEGER DEFAULT 0, detected_context_limit_model_key TEXT, needs_emergency_recovery INTEGER DEFAULT 0, emergency_recovery_origin TEXT DEFAULT '', upgrade_reminder_last_sent_at INTEGER, upgrade_reminder_count INTEGER NOT NULL DEFAULT 0, cached_m0_mural_data_url TEXT, cached_m0_mural_hash TEXT, coordinate_generation TEXT, coordinate_rebase_notice TEXT);
CREATE TABLE session_projects (
      session_id TEXT NOT NULL,
      harness TEXT NOT NULL DEFAULT 'opencode',
      project_path TEXT NOT NULL,
      updated_at INTEGER NOT NULL,
      PRIMARY KEY(session_id, harness)
    );
CREATE TABLE shadow_embedding_registrations (
      project_path TEXT NOT NULL,
      scope TEXT NOT NULL CHECK(scope IN ('memory', 'commit', 'chunk')),
      model_id TEXT NOT NULL,
      generation INTEGER NOT NULL DEFAULT 0,
      fingerprint TEXT NOT NULL DEFAULT '',
      table_epoch INTEGER NOT NULL DEFAULT 0,
      dims INTEGER NOT NULL DEFAULT 0,
      provenance_json TEXT NOT NULL DEFAULT '{}',
      updated_at INTEGER NOT NULL DEFAULT 0,
      PRIMARY KEY(project_path, scope, model_id)
    );
CREATE TABLE source_contents (
      tag_id INTEGER,
      session_id TEXT,
      content TEXT,
      created_at INTEGER, -- epoch ms; Date.now() on source writes, preserved on session clones
      harness TEXT NOT NULL DEFAULT 'opencode',
      PRIMARY KEY(session_id, tag_id)
    );
CREATE TABLE subagent_invocations (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      session_id TEXT NOT NULL,
      harness TEXT NOT NULL,
      subagent TEXT NOT NULL,
      task TEXT,
      provider_id TEXT,
      model_id TEXT,
      started_at INTEGER NOT NULL,
      ended_at INTEGER,
      status TEXT NOT NULL,
      input_tokens INTEGER NOT NULL DEFAULT 0,
      output_tokens INTEGER NOT NULL DEFAULT 0,
      cache_read_tokens INTEGER NOT NULL DEFAULT 0,
      cache_write_tokens INTEGER NOT NULL DEFAULT 0,
      error TEXT,
      parent_invocation_id INTEGER
    );
CREATE TABLE synapse_batch_ledger (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      session_id TEXT NOT NULL,
      project_path TEXT NOT NULL DEFAULT '',
      scope TEXT NOT NULL DEFAULT '',
      manifest_json TEXT NOT NULL DEFAULT '{}',
      request_key TEXT NOT NULL DEFAULT '',
      job_id TEXT,
      cursor TEXT,
      status TEXT NOT NULL DEFAULT 'pending',
      created_at INTEGER NOT NULL DEFAULT 0, -- epoch ms (Date.now())
      updated_at INTEGER NOT NULL DEFAULT 0,
      UNIQUE(session_id, request_key)
    );
CREATE TABLE tags (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      session_id TEXT,
      message_id TEXT,
      type TEXT,
      status TEXT DEFAULT 'active',
      byte_size INTEGER,
      tag_number INTEGER,
      harness TEXT NOT NULL DEFAULT 'opencode',
      entry_fingerprint TEXT,
      token_count INTEGER,
      input_token_count INTEGER,
      reasoning_token_count INTEGER, reasoning_byte_size INTEGER DEFAULT 0, drop_mode TEXT DEFAULT 'full', tool_name TEXT, input_byte_size INTEGER DEFAULT 0, caveman_depth INTEGER DEFAULT 0, tool_owner_message_id TEXT DEFAULT NULL,
      UNIQUE(session_id, tag_number)
    );
CREATE TABLE task_schedule_state (
      project_path  TEXT    NOT NULL,
      task          TEXT    NOT NULL,
      last_run_at   INTEGER,
      next_due_at   INTEGER,
      schedule      TEXT,
      last_status   TEXT,
      last_error    TEXT,
      last_checked_commit TEXT,
      last_broad_run_at INTEGER,
      retrospective_watermark_ms INTEGER,
      retry_count   INTEGER NOT NULL DEFAULT 0,
      PRIMARY KEY (project_path, task)
    );
CREATE TABLE tool_definition_measurements (
                    provider_id TEXT NOT NULL,
                    model_id TEXT NOT NULL,
                    agent_name TEXT NOT NULL,
                    tool_id TEXT NOT NULL,
                    token_count INTEGER NOT NULL,
                    recorded_at INTEGER NOT NULL,
                    PRIMARY KEY (provider_id, model_id, agent_name, tool_id)
                );
CREATE TABLE tool_owner_backfill_state (
      session_id TEXT PRIMARY KEY,
      status TEXT NOT NULL CHECK (status IN ('pending', 'running', 'completed', 'skipped')),
      started_at INTEGER,
      lease_expires_at INTEGER,
      completed_at INTEGER,
      last_error TEXT
    );
CREATE TABLE transform_decisions (
      session_id         TEXT    NOT NULL,
      harness            TEXT    NOT NULL DEFAULT 'opencode',
      message_id         TEXT    NOT NULL,
      ts_ms              INTEGER NOT NULL,
      decision           TEXT    NOT NULL,
      materialized       INTEGER NOT NULL DEFAULT 0,
      materialize_reason TEXT,
      system_hash_prev      TEXT,
      system_hash_new       TEXT,
      m0_tool_set_hash_prev TEXT,
      m0_tool_set_hash_new  TEXT,
      m0_model_key_prev     TEXT,
      m0_model_key_new      TEXT,
      emergency          INTEGER NOT NULL DEFAULT 0,
      dropped_tokens     INTEGER NOT NULL DEFAULT 0,
      dropped_count      INTEGER NOT NULL DEFAULT 0,
      input_tokens       INTEGER NOT NULL DEFAULT 0,
      PRIMARY KEY (session_id, harness, message_id)
    );
CREATE TABLE user_memories (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    content TEXT NOT NULL,
                    status TEXT NOT NULL DEFAULT 'active',
                    promoted_at INTEGER NOT NULL,
                    source_candidate_ids TEXT DEFAULT '[]',
                    source_candidate_provenance TEXT,
                    created_at INTEGER NOT NULL,
                    updated_at INTEGER NOT NULL
                );
CREATE TABLE user_memory_candidates (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    content TEXT NOT NULL,
                    session_id TEXT NOT NULL,
                    source_compartment_start INTEGER,
                    source_compartment_end INTEGER,
                    created_at INTEGER NOT NULL
                );
CREATE TABLE v22_backfill_failures (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      table_name TEXT NOT NULL,
      row_id INTEGER NOT NULL,
      raw_project_path TEXT NOT NULL,
      error_class TEXT NOT NULL CHECK (error_class IN ('not_git_repo', 'git_missing', 'git_timeout', 'permission_denied', 'unknown')),
      error_message TEXT,
      failed_at INTEGER NOT NULL,
      UNIQUE(table_name, row_id)
    );
CREATE TABLE v22_identity_rekey_map (
      old_project_path TEXT PRIMARY KEY,
      new_project_path TEXT NOT NULL,
      rekeyed_at INTEGER NOT NULL
    );
CREATE TABLE workspace_members (
      workspace_id INTEGER NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
      project_path TEXT NOT NULL,
      display_name TEXT NOT NULL,
      display_path TEXT NOT NULL,
      added_at INTEGER NOT NULL,
      PRIMARY KEY (workspace_id, project_path)
    );
CREATE TABLE workspaces (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      name TEXT NOT NULL UNIQUE,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      share_categories TEXT NOT NULL DEFAULT '["CONSTRAINTS"]'
    );
CREATE INDEX idx_cce_project_model ON compartment_chunk_embeddings(project_path, model_id);
CREATE INDEX idx_cce_session ON compartment_chunk_embeddings(session_id);
CREATE INDEX idx_compartment_events_session
      ON compartment_events(session_id);
CREATE INDEX idx_compartment_state_lease_expires
      ON compartment_state_lease(expires_at);
CREATE INDEX idx_compartments_session ON compartments(session_id);
CREATE INDEX idx_compression_depth_session ON compression_depth(session_id);
CREATE INDEX idx_dream_queue_pending ON dream_queue(started_at, enqueued_at);
CREATE INDEX idx_dream_queue_project ON dream_queue(project_path);
CREATE INDEX idx_dream_runs_project ON dream_runs(project_path, finished_at DESC);
CREATE INDEX idx_embedding_measurement_session
      ON embedding_measurement_corpus(session_id, created_at);
CREATE INDEX idx_git_commits_project_time
                    ON git_commits(project_path, committed_at DESC);
CREATE INDEX idx_git_sweep_coordinator_last_swept
      ON git_sweep_coordinator(last_swept_at);
CREATE INDEX idx_git_sweep_coordinator_lease_expires
      ON git_sweep_coordinator(lease_expires_at);
CREATE INDEX idx_historian_runs_session
      ON historian_runs(session_id, created_at DESC);
CREATE INDEX idx_historian_runs_status
      ON historian_runs(status, created_at DESC);
CREATE INDEX idx_identity_merge_log_identities
         ON identity_merge_log(from_identity, to_identity, merged_at);
CREATE INDEX idx_identity_merge_log_table_row
         ON identity_merge_log(table_name, row_id);
CREATE INDEX idx_m0_mutation_log_session ON m0_mutation_log(session_id);
CREATE INDEX idx_memories_project_category_hash ON memories(project_path, category, normalized_hash);
CREATE INDEX idx_memories_project_status_category ON memories(project_path, status, category);
CREATE INDEX idx_memories_project_status_expires ON memories(project_path, status, expires_at);
CREATE INDEX idx_memory_mutation_log_project
      ON memory_mutation_log(project_path, id);
CREATE INDEX idx_memory_mutation_log_target
      ON memory_mutation_log(project_path, target_memory_id, id);
CREATE INDEX idx_memory_mutation_log_visibility
      ON memory_mutation_log(project_path, category, id, target_memory_id);
CREATE INDEX idx_memory_verifications_memory ON memory_verifications(memory_id);
CREATE INDEX idx_message_fts_rowid_map_session_time
        ON message_fts_rowid_map(session_id, message_time_ms);
CREATE INDEX idx_message_history_index_orphan_sweep
        ON message_history_index(harness, session_id, updated_at);
CREATE INDEX idx_message_history_index_updated_at ON message_history_index(updated_at);
CREATE INDEX idx_message_history_source_session_ordinal
      ON message_history_source(session_id, message_ordinal);
CREATE INDEX idx_mirror_live_memory_content
                    ON mirror_live_memory_rows(module_project, category, normalized_hash);
CREATE INDEX idx_mirror_live_staging_generation
                    ON mirror_live_staging(generation);
CREATE INDEX idx_mirror_pending_reference_target
                    ON mirror_pending_references(domain, module_project, target_module_row_id);
CREATE INDEX idx_notes_project_status ON notes(project_path, status);
CREATE INDEX idx_notes_session_status ON notes(session_id, status);
CREATE INDEX idx_notes_smart_checks_due
                    ON notes(project_path, check_status, check_next_due_at)
                    WHERE type = 'smart' AND status = 'pending';
CREATE INDEX idx_notes_smart_checks_liveness
                    ON notes(project_path, check_false_since_at, check_last_liveness_at)
                    WHERE type = 'smart' AND status = 'pending';
CREATE INDEX idx_notes_type_status ON notes(type, status);
CREATE INDEX idx_pending_ops_session ON pending_ops(session_id);
CREATE INDEX idx_pending_ops_session_tag_id ON pending_ops(session_id, tag_id);
CREATE INDEX idx_plugin_messages_created
					ON plugin_messages(created_at);
CREATE INDEX idx_plugin_messages_direction_consumed
					ON plugin_messages(direction, consumed_at);
CREATE INDEX idx_primer_candidates_embedding_model
      ON primer_candidates(project_path, question_embedding_model_id);
CREATE UNIQUE INDEX idx_primer_candidates_occurrence
        ON primer_candidates(project_path, harness, session_id, source_start_message_id, source_end_message_id);
CREATE INDEX idx_primer_candidates_project_time
      ON primer_candidates(project_path, source_message_time);
CREATE INDEX idx_primer_candidates_session
      ON primer_candidates(session_id, harness);
CREATE INDEX idx_primers_embedding_model
      ON primers(project_path, question_embedding_model_id);
CREATE INDEX idx_primers_project_status_observed
      ON primers(project_path, status, last_observed_at DESC);
CREATE INDEX idx_project_key_files_generated_at ON project_key_files(project_path, generated_at);
CREATE INDEX idx_project_key_files_project ON project_key_files(project_path);
CREATE INDEX idx_recomp_compartments_session ON recomp_compartments(session_id);
CREATE INDEX idx_recomp_facts_session ON recomp_facts(session_id);
CREATE INDEX idx_sai_session_started
      ON subagent_invocations(session_id, started_at DESC);
CREATE INDEX idx_sai_subagent
      ON subagent_invocations(subagent, started_at DESC);
CREATE INDEX idx_session_facts_session ON session_facts(session_id);
CREATE INDEX idx_session_projects_project
      ON session_projects(project_path);
CREATE INDEX idx_source_contents_session ON source_contents(session_id);
CREATE INDEX idx_synapse_batch_ledger_session
      ON synapse_batch_ledger(session_id, updated_at);
CREATE INDEX idx_tags_active_session_tag_number
                ON tags(session_id, tag_number)
                WHERE status = 'active';
CREATE INDEX idx_tags_dropped_session_tag_number
                ON tags(session_id, tag_number)
                WHERE status = 'dropped';
CREATE INDEX idx_tags_pi_adopt
            ON tags(session_id, entry_fingerprint)
            WHERE type='message' AND entry_fingerprint IS NOT NULL;
CREATE INDEX idx_tags_pi_fallback_tool_owner
            ON tags(session_id, tool_owner_message_id)
            WHERE type='tool';
CREATE INDEX idx_tags_session_message_id ON tags(session_id, message_id);
CREATE INDEX idx_tags_session_tag_number ON tags(session_id, tag_number);
CREATE UNIQUE INDEX idx_tags_tool_composite
                ON tags(session_id, message_id, tool_owner_message_id)
                WHERE type = 'tool' AND tool_owner_message_id IS NOT NULL;
CREATE INDEX idx_tags_tool_null_owner
                ON tags(session_id, message_id)
                WHERE type = 'tool' AND tool_owner_message_id IS NULL;
CREATE INDEX idx_task_schedule_due ON task_schedule_state(next_due_at);
CREATE INDEX idx_tool_owner_backfill_state_status
      ON tool_owner_backfill_state(status);
CREATE INDEX idx_transform_decisions_session_harness
      ON transform_decisions(session_id, harness);
CREATE INDEX idx_um_status ON user_memories(status);
CREATE INDEX idx_umc_created ON user_memory_candidates(created_at);
CREATE UNIQUE INDEX idx_workspace_member_name ON workspace_members(workspace_id, display_name);
CREATE UNIQUE INDEX idx_workspace_member_unique ON workspace_members(project_path);
CREATE TRIGGER git_commits_fts_delete
                AFTER DELETE ON git_commits BEGIN
                    DELETE FROM git_commits_fts WHERE sha = OLD.sha;
                END;
CREATE TRIGGER git_commits_fts_insert
                AFTER INSERT ON git_commits BEGIN
                    DELETE FROM git_commits_fts WHERE sha = NEW.sha;
                    INSERT INTO git_commits_fts(sha, project_path, message)
                    VALUES (NEW.sha, NEW.project_path, NEW.message);
                END;
CREATE TRIGGER git_commits_fts_update
                AFTER UPDATE OF message, project_path ON git_commits BEGIN
                    DELETE FROM git_commits_fts WHERE sha = OLD.sha;
                    INSERT INTO git_commits_fts(sha, project_path, message)
                    VALUES (NEW.sha, NEW.project_path, NEW.message);
                END;
CREATE TRIGGER memories_ad AFTER DELETE ON memories BEGIN
      INSERT INTO memories_fts(memories_fts, rowid, content, category) VALUES ('delete', old.id, old.content, old.category);
    END;
CREATE TRIGGER memories_ai AFTER INSERT ON memories BEGIN
      INSERT INTO memories_fts(rowid, content, category) VALUES (new.id, new.content, new.category);
    END;
CREATE TRIGGER memories_au AFTER UPDATE ON memories BEGIN
      INSERT INTO memories_fts(memories_fts, rowid, content, category) VALUES ('delete', old.id, old.content, old.category);
      INSERT INTO memories_fts(rowid, content, category) VALUES (new.id, new.content, new.category);
    END;
CREATE TRIGGER memories_authority_guard_delete
            BEFORE DELETE ON memories
            WHEN (EXISTS (SELECT 1 FROM authority_managed WHERE project_path = OLD.project_path)
               OR EXISTS (SELECT 1 FROM authority_repair_pending WHERE project_path = OLD.project_path))
              AND COALESCE((SELECT enabled FROM context_privilege_state WHERE id = 1), 0) = 0
            BEGIN SELECT RAISE(ABORT, 'context.db memory writes are managed by the Rust module'); END;
CREATE TRIGGER memories_authority_guard_insert
            BEFORE INSERT ON memories
            WHEN (EXISTS (SELECT 1 FROM authority_managed WHERE project_path = NEW.project_path)
               OR EXISTS (SELECT 1 FROM authority_repair_pending WHERE project_path = NEW.project_path))
              AND COALESCE((SELECT enabled FROM context_privilege_state WHERE id = 1), 0) = 0
            BEGIN SELECT RAISE(ABORT, 'context.db memory writes are managed by the Rust module'); END;
CREATE TRIGGER memories_authority_guard_update
            BEFORE UPDATE ON memories
            WHEN (EXISTS (SELECT 1 FROM authority_managed WHERE project_path = OLD.project_path)
               OR EXISTS (SELECT 1 FROM authority_managed WHERE project_path = NEW.project_path)
               OR EXISTS (SELECT 1 FROM authority_repair_pending WHERE project_path = OLD.project_path)
               OR EXISTS (SELECT 1 FROM authority_repair_pending WHERE project_path = NEW.project_path))
              AND COALESCE((SELECT enabled FROM context_privilege_state WHERE id = 1), 0) = 0
            BEGIN SELECT RAISE(ABORT, 'context.db memory writes are managed by the Rust module'); END;
CREATE TRIGGER notes_authority_guard_delete
            BEFORE DELETE ON notes
            WHEN (
        EXISTS (SELECT 1 FROM authority_managed WHERE project_path = OLD.project_path)
        OR EXISTS (SELECT 1 FROM authority_repair_pending WHERE project_path = OLD.project_path)
        OR EXISTS (
            SELECT 1 FROM session_projects sp
            JOIN authority_managed am ON am.project_path = sp.project_path
            WHERE sp.session_id = OLD.session_id
        )
        OR EXISTS (
            SELECT 1 FROM session_projects sp
            JOIN authority_repair_pending arp ON arp.project_path = sp.project_path
            WHERE sp.session_id = OLD.session_id
        )
    ) AND COALESCE((SELECT enabled FROM context_privilege_state WHERE id = 1), 0) = 0
            BEGIN SELECT RAISE(ABORT, 'context.db note writes are managed by the Rust module'); END;
CREATE TRIGGER notes_authority_guard_insert
            BEFORE INSERT ON notes
            WHEN (
        EXISTS (SELECT 1 FROM authority_managed WHERE project_path = NEW.project_path)
        OR EXISTS (SELECT 1 FROM authority_repair_pending WHERE project_path = NEW.project_path)
        OR EXISTS (
            SELECT 1 FROM session_projects sp
            JOIN authority_managed am ON am.project_path = sp.project_path
            WHERE sp.session_id = NEW.session_id
        )
        OR EXISTS (
            SELECT 1 FROM session_projects sp
            JOIN authority_repair_pending arp ON arp.project_path = sp.project_path
            WHERE sp.session_id = NEW.session_id
        )
    ) AND COALESCE((SELECT enabled FROM context_privilege_state WHERE id = 1), 0) = 0
            BEGIN SELECT RAISE(ABORT, 'context.db note writes are managed by the Rust module'); END;
CREATE TRIGGER notes_authority_guard_update
            BEFORE UPDATE ON notes
            WHEN ((
        EXISTS (SELECT 1 FROM authority_managed WHERE project_path = OLD.project_path)
        OR EXISTS (SELECT 1 FROM authority_repair_pending WHERE project_path = OLD.project_path)
        OR EXISTS (
            SELECT 1 FROM session_projects sp
            JOIN authority_managed am ON am.project_path = sp.project_path
            WHERE sp.session_id = OLD.session_id
        )
        OR EXISTS (
            SELECT 1 FROM session_projects sp
            JOIN authority_repair_pending arp ON arp.project_path = sp.project_path
            WHERE sp.session_id = OLD.session_id
        )
    ) OR (
        EXISTS (SELECT 1 FROM authority_managed WHERE project_path = NEW.project_path)
        OR EXISTS (SELECT 1 FROM authority_repair_pending WHERE project_path = NEW.project_path)
        OR EXISTS (
            SELECT 1 FROM session_projects sp
            JOIN authority_managed am ON am.project_path = sp.project_path
            WHERE sp.session_id = NEW.session_id
        )
        OR EXISTS (
            SELECT 1 FROM session_projects sp
            JOIN authority_repair_pending arp ON arp.project_path = sp.project_path
            WHERE sp.session_id = NEW.session_id
        )
    )) AND COALESCE((SELECT enabled FROM context_privilege_state WHERE id = 1), 0) = 0
            BEGIN SELECT RAISE(ABORT, 'context.db note writes are managed by the Rust module'); END;
CREATE TRIGGER primers_ad AFTER DELETE ON primers BEGIN
      INSERT INTO primers_fts(primers_fts, rowid, question, answer, project_path)
      VALUES ('delete', old.id, old.question, old.answer, old.project_path);
    END;
CREATE TRIGGER primers_ai AFTER INSERT ON primers BEGIN
      INSERT INTO primers_fts(rowid, question, answer, project_path)
      VALUES (new.id, new.question, new.answer, new.project_path);
    END;
CREATE TRIGGER primers_au AFTER UPDATE ON primers BEGIN
      INSERT INTO primers_fts(primers_fts, rowid, question, answer, project_path)
      VALUES ('delete', old.id, old.question, old.answer, old.project_path);
      INSERT INTO primers_fts(rowid, question, answer, project_path)
      VALUES (new.id, new.question, new.answer, new.project_path);
    END;
CREATE TRIGGER tags_version_ad AFTER DELETE ON tags BEGIN
      INSERT INTO session_meta(
        session_id, harness, last_response_time, cache_ttl, counter, tags_version,
        last_nudge_tokens, last_nudge_band, last_transform_error, is_subagent,
        last_context_percentage, last_input_tokens, observed_safe_input_tokens,
        cache_alert_sent, times_execute_threshold_reached, compartment_in_progress,
        system_prompt_hash, cleared_reasoning_through_tag
      ) VALUES(OLD.session_id, OLD.harness, 0, '5m', 0, 1, 0, '', '', 0, 0, 0, 0, 0, 0, 0, '', 0)
      ON CONFLICT(session_id) DO UPDATE SET tags_version = tags_version + 1;
    END;
CREATE TRIGGER tags_version_ai AFTER INSERT ON tags BEGIN
      INSERT INTO session_meta(
        session_id, harness, last_response_time, cache_ttl, counter, tags_version,
        last_nudge_tokens, last_nudge_band, last_transform_error, is_subagent,
        last_context_percentage, last_input_tokens, observed_safe_input_tokens,
        cache_alert_sent, times_execute_threshold_reached, compartment_in_progress,
        system_prompt_hash, cleared_reasoning_through_tag
      ) VALUES(NEW.session_id, NEW.harness, 0, '5m', 0, 1, 0, '', '', 0, 0, 0, 0, 0, 0, 0, '', 0)
      ON CONFLICT(session_id) DO UPDATE SET tags_version = tags_version + 1;
    END;
CREATE TRIGGER tags_version_au
    AFTER UPDATE OF session_id, message_id, tag_number, type, tool_owner_message_id, status ON tags BEGIN
      INSERT INTO session_meta(
        session_id, harness, last_response_time, cache_ttl, counter, tags_version,
        last_nudge_tokens, last_nudge_band, last_transform_error, is_subagent,
        last_context_percentage, last_input_tokens, observed_safe_input_tokens,
        cache_alert_sent, times_execute_threshold_reached, compartment_in_progress,
        system_prompt_hash, cleared_reasoning_through_tag
      ) VALUES(OLD.session_id, OLD.harness, 0, '5m', 0, 1, 0, '', '', 0, 0, 0, 0, 0, 0, 0, '', 0)
      ON CONFLICT(session_id) DO UPDATE SET tags_version = tags_version + 1;
      INSERT INTO session_meta(
        session_id, harness, last_response_time, cache_ttl, counter, tags_version,
        last_nudge_tokens, last_nudge_band, last_transform_error, is_subagent,
        last_context_percentage, last_input_tokens, observed_safe_input_tokens,
        cache_alert_sent, times_execute_threshold_reached, compartment_in_progress,
        system_prompt_hash, cleared_reasoning_through_tag
      )
      SELECT NEW.session_id, NEW.harness, 0, '5m', 0, 1, 0, '', '', 0, 0, 0, 0, 0, 0, 0, '', 0
      WHERE NEW.session_id != OLD.session_id
      ON CONFLICT(session_id) DO UPDATE SET tags_version = tags_version + 1;
    END;
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (1, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (2, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (3, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (4, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (5, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (6, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (7, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (8, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (9, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (10, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (11, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (12, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (13, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (14, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (15, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (16, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (17, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (18, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (19, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (20, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (21, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (22, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (23, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (24, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (25, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (26, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (27, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (28, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (29, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (30, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (31, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (32, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (33, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (34, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (35, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (36, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (37, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (38, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (39, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (40, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (41, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (42, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (43, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (44, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (45, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (46, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (47, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (48, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (49, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (50, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (51, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (52, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (53, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (54, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (55, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (56, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (57, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (58, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (59, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (60, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (61, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (62, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (63, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (64, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (65, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (66, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (67, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (68, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (69, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (70, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (71, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (72, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (73, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (74, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (75, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (76, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (77, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (78, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (79, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (80, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (81, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (82, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (83, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (84, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (85, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (86, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (87, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (88, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (89, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (90, 'snapshot', 0);
INSERT OR IGNORE INTO schema_migrations (version, description, applied_at) VALUES (91, 'snapshot', 0);
